# GoReleaser configuration for agent-team-release
# Documentation: https://goreleaser.com

version: 2

project_name: agent-team-release

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: agent-team-release
    main: ./cmd/releaseagent
    binary: agent-team-release
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: agent-team-release
    builds:
      - agent-team-release
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Performance
      regexp: '^perf'
      order: 2
    - title: Refactoring
      regexp: '^refactor'
      order: 3
    - title: Other
      order: 999

release:
  github:
    owner: agentplexus
    name: agent-team-release
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }}

    {{ .TagSubject }}

  footer: |
    ---

    **Full Changelog**: https://github.com/agentplexus/agent-team-release/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    ```bash
    # Go install
    go install github.com/agentplexus/agent-team-release/cmd/releaseagent@{{ .Tag }}

    # Homebrew (macOS/Linux)
    brew tap agentplexus/tap
    brew install agent-team-release
    ```

brews:
  - name: agent-team-release
    ids:
      - agent-team-release
    repository:
      owner: agentplexus
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/agentplexus/agent-team-release
    description: Multi-agent release preparation team for multi-language repositories
    license: MIT
    dependencies:
      - name: git
      - name: gh
    test: |
      system "#{bin}/agent-team-release", "version"
    install: |
      bin.install "agent-team-release"

announce:
  skip: true

